name: Sync Gitee Repository

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/**"
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-22.04
    if: vars.GITEE_REPO != ''
    env:
      SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
      GITEE_REPOSITORY: ${{ vars.GITEE_OWNER }}/${{ vars.GITEE_REPO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Private Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Push Mirror
        env:
          SOURCE_REPO: "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          DESTINATION_REPO: "git@gitee.com:${{ env.GITEE_REPOSITORY }}.git"
        run: |
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror